In [ ]:
#Numpy -numerical python -library used for workingwith arrays
#source code for numpy is loacted at this github repository
#https://github.com/numpy/numpy
import numpy as np
arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
#Dimensions in Arrays
#nested arrays -these are arrays that have arrays as their element
#there are 0-D , 1-D,2-D ,3-D arrays

#0-D array

import numpy as np
arr = np.array(42)
print(arr)

42


In [ ]:
#1-D array

import numpy as np
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [ ]:
#2-D array

import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
#3-D array

import numpy as np
# Original: arr = np.array([[[21,54,34],[85,53,87]],[[54,54,54]]])
# Fix: Ensure all 2D sub-arrays have the same shape to avoid inhomogeneity.
arr = np.array([[[21,54,34]],[[54,54,54]]])
print(arr)

[[[21 54 34]]

 [[54 54 54]]]


In [ ]:
# arry indexing
#1-D
import numpy as np
arr = np.array([1,2,3,4])
print(arr[0])

1


In [ ]:
#array indexing
#2-D[dimension,index]
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print('2nd element on 1st row:',arr[0,1])

2nd element on1st row: 2


In [ ]:
#array indexing
#3-D
import numpy as np
arr=np.array([[[1,2,3],[1,5,6]],
 [[1,5,6],[5,6,7]]])
print(arr[1,0,1])

5


In [ ]:
#array slicing
#[start:end]
#[start:end:step]
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[:])

[1 2 3 4 5 6 7]


In [ ]:
#to check how many dimension array is having
#we use ndim attribute
import numpy as np
a = np.array(42)
b = np.array([1,2,3,4])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
#higher dimensional arrays--we define the no of dimensons by using the
#attribute ndmin
import numpy as np
arr = np.array([1,2,3,4,5],ndmin=5)
print(arr)
print('number of dimensions:',arr.ndim)


[[[[[1 2 3 4 5]]]]]
number of dimensions: 5


Resulting Shape: (1, 1, 2, 2, 3)

Dimensions 0 and 1 were added because of ndmin=5 (sizes are 1).

Dimensions 2, 3, and 4 come from the shape of the input data itself (2 blocks, 2 rows, 3 columns).


In [ ]:
#shaping of array --shape of the array is the no of elements in each dimension
#numpy have an attribute called shape the returns a tuple with each index having
#no of corresponding elements

#create an array with 5 dimension using ndim and a vector with values 1,2,3,4
#and verify the last dimension has value 4
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]],ndmin =5)
print(arr)
print('Shape of the array:',arr.shape)

[[[[[1 2 3]
    [4 5 6]]

   [[1 2 3]
    [4 5 6]]]]]
Shape of the array: (1, 1, 2, 2, 3)


In [ ]:
#reshaping of arrays Reshaping is done from 1-D to 2-D and 1-D to 3-D
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
newarr = arr.reshape(1,1,1,3,3)
print(newarr)

[[[[[1 2 3]
    [4 5 6]
    [7 8 9]]]]]


In [ ]:
#flattening of arrays --converting multidimensional array into 1-D array
import numpy as np
arr = np.array([[1,2,3,4,5,6,7,8,9,10,11,12],[1,2,3,4,5,6,7,8,8,10,11,12]])
new_arr = arr.reshape(-1)
print(new_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12  1  2  3  4  5  6  7  8  8 10 11 12]


In [ ]:
# random module to generate no which cannot be predicted logiaclly
import numpy as np
from numpy import random

In [ ]:
# to generate a random no between 1 to 100
import numpy as np
from numpy import random
x = random.randint(100)
print(x)

50


In [ ]:
# for generating a random float no between 0 to 1
import numpy as np
from numpy import random
x = random.rand(1)
print(x)

[0.19987253]


In [ ]:
# for generating random array
# for generating a 1-D array containing 5 random integers from 0 to 100
from numpy import random
x = random.randint(100,size = 5)
print(x)

[99 47 39 45 59]


In [ ]:
# to generate a 2-D array with 5 random floats
from numpy import random
x = random.rand(2,5)
print(x)

[[0.4439949  0.81649389 0.3110912  0.66680986 0.45870461]
 [0.03481932 0.6201648  0.9274239  0.4972189  0.59682858]]


In [ ]:
# to generate a 3-D array with 5 random floats
from numpy import random
x = random.rand(3,5,7)
print(x)

[[[0.01730547 0.50020175 0.97534309 0.90300343 0.27499819 0.17661445
   0.76911255]
  [0.64560781 0.17986777 0.22944604 0.86528685 0.53740791 0.98296211
   0.58220431]
  [0.87672682 0.26410169 0.69335    0.57725753 0.4477813  0.57964051
   0.14194727]
  [0.13897004 0.98727925 0.41089122 0.89444864 0.72102935 0.69356974
   0.84427176]
  [0.25080403 0.5850163  0.98401547 0.46164803 0.4216433  0.41532895
   0.59989894]]

 [[0.41869559 0.03559053 0.45523791 0.17258397 0.24072818 0.68020151
   0.85755052]
  [0.44200337 0.18810654 0.98896157 0.07286986 0.51405409 0.54679051
   0.67299317]
  [0.02428098 0.61906131 0.08165178 0.53162829 0.82789354 0.62163896
   0.07961792]
  [0.06208792 0.42542898 0.9465026  0.7101405  0.75834461 0.36290953
   0.86991614]
  [0.14411046 0.90110469 0.28285531 0.52245239 0.85379607 0.47640387
   0.38552648]]

 [[0.18358442 0.54938833 0.04497698 0.40922666 0.44662318 0.91047549
   0.65938991]
  [0.83397914 0.48521188 0.41583049 0.47787451 0.40428835 0.85406021
   

In [ ]:
#  choice()  choice method
from numpy import random
x = random.choice([3,5,4,65],size=(3,5))
print(x)

[[ 5  4 65  5  4]
 [ 3 65 65  3 65]
 [ 5  3  3  4  3]]


In [ ]:
# shuffle() changes the original array and
# permutation() does not change the original array

from numpy import random
arr = np.array([1,2,3,4,5])
random.shuffle(arr)
print(arr)


[3 2 4 5 1]


In [ ]:
from numpy import random
arr = np.array([1,2,3,4,5])
random.permutation(arr)
print(random.permutation(arr))

[4 1 5 3 2]


In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr[:,1])



[2 5]


In [ ]:
# ufuncs --universal functions
# vectorization --process of iterative statements into vector-based operations

x = [1,2,3,4]
y = [5,6,7,8]
z = np.add(x,y)
print(z)

#create your own ufunctions
def myadd(x,y):
  return x+y
myadd = np.frompyfunc(myadd,2,1)
print(myadd([1,2,3,4],[5,6,7,8]))

# ufuncs oprations add(), subtract(),multiply(),power(),mod(),remainder(),divmod(),exp(),log(),sqrt(),minimum(),maximum(),sum(),cumsum(),prod(),cumprod(),diff()
# add(),subtract(),divide(),multiply()
import numpy as np
arr1 = np.array([10,11,12,13,14,15])
arr2 = np.array([20,21,22,23,24,25])
newarr = np.add(arr1,arr2)
newarr1 = np.subtract(arr1,arr2)
newarr2 = np.divide(arr1,arr2)
newarr3 = np.multiply(arr1,arr2)
print(newarr)
print(newarr1)
print(newarr2)
print(newarr3)


[ 6  8 10 12]
[6 8 10 12]
[30 32 34 36 38 40]
[-10 -10 -10 -10 -10 -10]
[0.5        0.52380952 0.54545455 0.56521739 0.58333333 0.6       ]
[200 231 264 299 336 375]


In [ ]:
import numpy as np
a = np.array([10, 20 ,30,40,50,60])
b= np.array([1,2,3,4,5,6])
# Arr= np.divmod(a,b)
# arr = np.mod(a,b)
arr = np.remainder(a,b)
print(arr)

[0 0 0 0 0 0]


In [ ]:
import numpy as np
arr1 = np.array([10,20,30,40,50,60])
arr2 = np.array([2,5,10,8,13,21])
newarr = np.power(arr1,arr2)
print(newarr)

[                 100              3200000      590490000000000
        6553600000000 -4713326795723169792   377523914466656256]


In [ ]:
'''newarr = np.mod(arr1,arr2)'''
'''newarr = np.remainder(arr1,arr2)'''
import numpy as np
x = np.array([1,2,3])
exp_arr = np.exp(x)
print(exp_arr)


[ 2.71828183  7.3890561  20.08553692]


In [ ]:
# log
# import numpy as np
# a = np.array([1,3,9])
# r = np.log(a)
# print(r)
# log(exp(x))
import numpy as np
v = np.exp([1,2])
r = np.log(v)
print(v)

[2.71828183 7.3890561 ]


In [ ]:
# square root
import numpy as np
a = np.array([1,4,9,16,25])
b = np.sqrt(a)
print(b)

[1. 2. 3. 4. 5.]


In [ ]:
# minimum and maximum
import numpy as np
a = np.array([2,8,125])
b = np.array([3,3,15])
print(np.maximum(a,b))
print(np.minimum(a,b))

[  3   8 125]
[ 2  3 15]


In [ ]:
# summation
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
newarr = np.sum([arr1,arr2])
print(newarr)
# summation over axis
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
newarr = np.sum([arr1,arr2],axis=1)
print(newarr)

12
[6 6]


In [ ]:
# cumulative summation--cumsum()
import numpy as np
arr = np.array([1,2,3,4,5,6])
newarr = np.cumsum(arr)
print(newarr)

[ 1  3  6 10 15 21]


In [ ]:
# product of an array
import numpy as np
arr = np.array([1,2,3,4])
x = np.prod(arr)
print(x)

24


In [ ]:
# product of 2 arrays
import numpy as np
arr1 = np.array([2,4,6,8])
arr2 = np.array([1,3,5,7,])
x = np.prod([arr1,arr2],axis=1)
print(x)


[384 105]


In [ ]:
# cumulative product --cumprod()
import numpy as np
arr = np.array([1,2,3,4])
x = np.cumprod(arr)
print(x)

[ 1  2  6 24]


In [ ]:
# discrete difference
# [1,2,3,4] [2-1,3-2,4-3] [1,1,1]
import numpy as np
arr = np.array([10,15,20,25])
x = np.diff([arr],axis = 1)
print(x)

[[5 5 5]]


In [ ]:
# join numpy arrays
# putting the content of 2 or more arrays in single array thru
# concatenate function concatenate()
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
# class task--join two 2-D arrays along axis
import numpy as np
arr1 = np.array([[1,3,5],[2,4,6]])
arr2 = np.array([[7,9,11],[8,10,12]])
arr = np.concatenate((arr1,arr2),axis=1)
print(arr)

[[ 1  3  5  7  9 11]
 [ 2  4  6  8 10 12]]


In [ ]:
# join arrays using stack functions --it is same as concatenate the only difference is that stacking is done along new axis
#Type of Stacks-- hstack(),vstack(),dstack()
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.stack((arr1,arr2),axis=1)
arr = np.hstack((arr1,arr2)) #creates 1-d array
arr = np.vstack((arr1,arr2)) #creates 2-d array
arr = np.dstack((arr1,arr2)) #creates 3-d array
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [ ]:
#splitting means breaking the array into multiple
#array_split()method
#types of split()--hsplit(),vsplit(),dsplit()
import numpy as np
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,4)
print(newarr)
print(newarr[0])
print(newarr[1])
print(newarr[2])
print(newarr[3])


[array([1, 2]), array([3, 4]), array([5]), array([6])]
[1 2]
[3 4]
[5]
[6]


In [ ]:
#we can search an array for a certain value and return
#the indexes that get a muatch,to search an array we use where() function
import numpy as np
arr = np.array([1,2,3,4,5,4,4])
x = np.where(arr==4)
print(x)

(array([3, 5, 6]),)


In [ ]:
#class task split the 2-D array into 3-D array
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
newarr = np.array_split(arr, 4)
print(newarr)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]]), array([[10, 11, 12]])]


In [ ]:
#class task split the 2-d array having 3 elements each into 3 2-d arrays

In [ ]:
#class task find the indexes where the values are odd
x = np.array([10,14,93,41,8,7])
a = np.where(x%2==1)
print(a)

(array([2, 3, 5]),)


In [ ]:
# search sorted()
import numpy as np
arr = np.array([6,7,8,9])
x = np.searchsorted(arr,7)
print(x)

1


In [ ]:
# sort()
# sort the array //sort creates a copy of the array leaving the original array
import numpy as np
arr = np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]
